### ISSUE TITLE
Unable to run clinvar_xml_parser dataloader

### ISSUE THREAD

**Issue by dmyung** [SuLab/myvariant.info#12]
The clinvar_xml_parser.py data loader is referencing a clinvar or clinvar1 import that is not listed in the requirements:
https://github.com/SuLab/myvariant.info/blob/master/src/dataload/contrib/clinvar/clinvar_xml_parser.py#L5

It's changed from clinvar to clinvar1 - is the clinvar library that does the parseString() call available from you or is it a separate 3rd party lib to be installed? 

https://github.com/SuLab/myvariant.info/blob/master/src/dataload/contrib/clinvar/clinvar_xml_parser.py#L315
`            record_parsed = clinvar1.parseString(record, silence=1)`

**Comment by newgene** [comment]
It's a code typo was fixed in recent commits.
