### ISSUE TITLE
Incorrect HGVS name creation from VCF file

### ISSUE THREAD

**Issue by Mazzafish** [SuLab/myvariant.info#16]

**Comment by Mazzafish** [comment]
Whenever using the function get_hgvs_from_vcf, variants with two entries as Alt allele (for instance https://samtools.github.io/hts-specs/VCFv4.2.pdf, 3rd and 5th variant on the vcf sample file) gain its own place in the list of variants extracted from the VCF file. This was noticed when running `mv.getvariants(variant_list)` and getting as output a few more variants than originally expected. 

    As a preview of what myvariant outputs in those instances:
    {u'query': u'GTTT', u'notfound': True}
    {u'query': u'CAAAAAAAAA', u'notfound': True}
    {u'query': u'AGTGT', u'notfound': True}
    ...
    {u'query': u'AGTTTT', u'notfound': True}

**Comment by newgene** [comment]
Hi Mazzafish,

This should be an issue for [myvariant.py](https://github.com/SuLab/myvariant.py) repo. We have just [solved this issue] (https://github.com/SuLab/myvariant.py/commit/d55d7461885e0ae46ea48c0f8f42c311f0ef7483) where an ALT column has multiple alleles. We also made some improvement on the [handling of some other VCF edge cases](https://github.com/SuLab/myvariant.py/commit/392cbb61f10f38c55620871ce5d5c267bd635b1e).

**Comment by Mazzafish** [comment]
Awesome, I'll test it out. Thanks for the response.

**Comment by newgene** [comment]
And just a note, you will need to test the latest code from [myvariant.py](https://github.com/SuLab/myvariant.py) repo, as we have not released a new version to PyPI yet.
