### ISSUE TITLE
variant normalization

### ISSUE THREAD

**Issue by jma7** [SuLab/myvariant.info#21]
Hi, 
  We are wondering how the variant normalization is done in myvariant.info? When you import the variants from each database, do you do any sort of internal variant normalization or just take the chr,pos,ref,alt directly from the source?

Thanks

**Comment by newgene** [comment]
Hi @jma7, we do some simple normalization like make sure it's 1-based if the input source is 0-based, and also skipped those variants cannot be represented cleanly with genomic-coordinate based HGVS ids. Internally, we also verify each variants against the hg19 and hg38 genome assemblies, to make sure the ref allele matches with the coordinates. But for those small portion of variants which do not match the reference genomes, we currently do not discard them, and plan to add a validation flag to each variant object.

**Comment by jma7** [comment]
Hi Chunlei,
  Thanks for the quick response. I have a more specific question/suggestion. 
  We have two variants ['5', '170837543', 'C', 'CTCTG'] and ['5', '170837547', 'G', 'GTCTG'] with hgvs ID chr5:g.170837543_170837544insTCTG and chr5:g.170837547_170837548insTCTG. These two variants are actually the same which is ['5', 170837544, '-', 'TCTG'] after normalization. When I search for chr5:g.170837543_170837544insTCTG, there is information returned. But when I search for chr5:g.170837547_170837548insTCTG, there is 404 not found. So it seems currently there is no internal normalization to normalize ['5', '170837547', 'G', 'GTCTG'] to return correct information. Hopefully there will be a fix in the future for this issue. 

Thanks

**Comment by newgene** [comment]
@jma7 Ok, the specific example helps me understand better what you ask originally. Variant normalization can happen two places:

1. When we load variant annotations from a data source, esp. its data file is provided as a VCF file, we do some level of variant normalization (such as CTTTT/CT --> TTTT/T, TC/TG --> C/G). But we don't do any further normalization which requires to compare to the reference genome (like the case you mentioned). Thus, two variants ['5', '170837543', 'C', 'CTCTG'] and ['5', '170837547', 'G', 'GTCTG'] from a VCF file, will become two variant objects in MyVariant.info. 
   
   Ideally, we should expect the input VCF files are all normalized, but it may not be always the case. We will consider to normalize the input VCF files with tools like [vt](http://genome.sph.umich.edu/wiki/Vt#Normalization) in the future, that way, we can remove those possible redundant variants.

2. When users query MyGene.info with a HGVS id, like "chr5:g.170837547_170837548insTCTG", we don't perform any normalization on it, so it will return no match. We would like to leave the normalization step to users in such cases.
