### ISSUE TITLE
Discrepancies in returned COSMIC ids

### ISSUE THREAD

**Issue by acoffman** [SuLab/myvariant.info#25]
Hi!

We've noticed that there seem to be some inconsistencies with the COSMIC data being returned in the variant annotation service. 

Here's an example query:

`GET myvariant.info/v1/variant/chr4:g.55141036T>C?fields=cosmic,mutdb`

And the response:
```json
{
    "_id": "chr4:g.55141036T>C",
    "_version": 2,
    "cosmic": {
        "alt": "C",
        "chrom": "4",
        "cosmic_id": "COSM1430077",
        "hg19": {
            "end": 55141036,
            "start": 55141036
        },
        "mut_freq": 0.14,
        "mut_nt": "T>C",
        "ref": "T",
        "tumor_site": "large_intestine"
    },
    "mutdb": {
        "alt": "C",
        "chrom": "4",
        "cosmic_id": "85787",
        "hg19": {
            "end": 55141036,
            "start": 55141036
        },
        "mutpred_score": -1,
        "ref": "T",
        "rsid": null,
        "strand": "p"
    }
}
```

The cosmic id returned in the `cosmic` top level key (`body['cosmic']['cosmid_id']` doesn't match the cosmic id returned in the `mutdb` top level key (`body['mutdb']['cosmic_id']`). Additionally, the cosmic id returned in the `cosmic` section isn't a valid cosmic id at all, while the one in the `mutdb` section appears to be the correct one for the variant in question.

I assume this is likely to come from discrepancies in the underlying data sources, but it was a little surprising to find a non-existent cosmic id in the `cosmic` section.

**Comment by newgene** [comment]
@acoffman my reply at #20 should also apply here. Basically, we have a very old version of Cosmic due to license restriction.

And I have also verified that "COSM1430077" is indeed coming from UCSC cosmic and cosmicRaw tables:

```
❯ zgrep COSM1430077 cosmic.txt.gz
1005	chr4	55141035	55141036	COSM1430077
❯ zgrep COSM1430077 cosmicRaw.txt.gz
COSMIC v68	COSM1430077	PDGFRA	ENST00000257290	Substitution - Missense	c.1682T>C	p.V561A	4	551410355141036	t>c	V>A	large_intestine	1	725	.14
```
